all: false
dir: '{{.InterfaceDir}}/mocks'
filename: 'mock_{{.InterfaceName| snakecase}}.gen.go'
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: 'mocks'
packages:
  github.com/bazueva/gofermart/internal/service/order:
    config:
      all: true
  github.com/bazueva/gofermart/internal/service/user:
    config:
      all: true
  github.com/bazueva/gofermart/internal/interfaces:
    config:
      all: true
  github.com/bazueva/gofermart/internal/middleware:
    config:
      all: true
  github.com/bazueva/gofermart/internal/app:
    config:
      all: true
  github.com/bazueva/gofermart/internal/handler:
    config:
      all: true