// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderQueue creates a new instance of MockOrderQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderQueue {
	mock := &MockOrderQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderQueue is an autogenerated mock type for the OrderQueue type
type MockOrderQueue struct {
	mock.Mock
}

type MockOrderQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderQueue) EXPECT() *MockOrderQueue_Expecter {
	return &MockOrderQueue_Expecter{mock: &_m.Mock}
}

// AddOrderIDToQueue provides a mock function for the type MockOrderQueue
func (_mock *MockOrderQueue) AddOrderIDToQueue(orderID string) {
	_mock.Called(orderID)
	return
}

// MockOrderQueue_AddOrderIDToQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrderIDToQueue'
type MockOrderQueue_AddOrderIDToQueue_Call struct {
	*mock.Call
}

// AddOrderIDToQueue is a helper method to define mock.On call
//   - orderID string
func (_e *MockOrderQueue_Expecter) AddOrderIDToQueue(orderID any) *MockOrderQueue_AddOrderIDToQueue_Call {
	return &MockOrderQueue_AddOrderIDToQueue_Call{Call: _e.mock.On("AddOrderIDToQueue", orderID)}
}

func (_c *MockOrderQueue_AddOrderIDToQueue_Call) Run(run func(orderID string)) *MockOrderQueue_AddOrderIDToQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrderQueue_AddOrderIDToQueue_Call) Return() *MockOrderQueue_AddOrderIDToQueue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderQueue_AddOrderIDToQueue_Call) RunAndReturn(run func(orderID string)) *MockOrderQueue_AddOrderIDToQueue_Call {
	_c.Run(run)
	return _c
}
