// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWaiting creates a new instance of MockWaiting. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWaiting(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWaiting {
	mock := &MockWaiting{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWaiting is an autogenerated mock type for the Waiting type
type MockWaiting struct {
	mock.Mock
}

type MockWaiting_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWaiting) EXPECT() *MockWaiting_Expecter {
	return &MockWaiting_Expecter{mock: &_m.Mock}
}

// Wait provides a mock function for the type MockWaiting
func (_mock *MockWaiting) Wait(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWaiting_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockWaiting_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWaiting_Expecter) Wait(ctx any) *MockWaiting_Wait_Call {
	return &MockWaiting_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *MockWaiting_Wait_Call) Run(run func(ctx context.Context)) *MockWaiting_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWaiting_Wait_Call) Return(err error) *MockWaiting_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWaiting_Wait_Call) RunAndReturn(run func(ctx context.Context) error) *MockWaiting_Wait_Call {
	_c.Call.Return(run)
	return _c
}
