// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bazueva/gofermart/internal/domain/entities"
	"github.com/bazueva/gofermart/internal/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BeginTransaction provides a mock function for the type MockRepository
func (_mock *MockRepository) BeginTransaction(ctx context.Context) (interfaces.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 interfaces.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (interfaces.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) interfaces.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_BeginTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTransaction'
type MockRepository_BeginTransaction_Call struct {
	*mock.Call
}

// BeginTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) BeginTransaction(ctx any) *MockRepository_BeginTransaction_Call {
	return &MockRepository_BeginTransaction_Call{Call: _e.mock.On("BeginTransaction", ctx)}
}

func (_c *MockRepository_BeginTransaction_Call) Run(run func(ctx context.Context)) *MockRepository_BeginTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_BeginTransaction_Call) Return(tx interfaces.Tx, err error) *MockRepository_BeginTransaction_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockRepository_BeginTransaction_Call) RunAndReturn(run func(ctx context.Context) (interfaces.Tx, error)) *MockRepository_BeginTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// CountOrdersByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) CountOrdersByUserID(ctx context.Context, orderFilter entities.OrderFilter) (int32, *entities.DomainError) {
	ret := _mock.Called(ctx, orderFilter)

	if len(ret) == 0 {
		panic("no return value specified for CountOrdersByUserID")
	}

	var r0 int32
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.OrderFilter) (int32, *entities.DomainError)); ok {
		return returnFunc(ctx, orderFilter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.OrderFilter) int32); ok {
		r0 = returnFunc(ctx, orderFilter)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.OrderFilter) *entities.DomainError); ok {
		r1 = returnFunc(ctx, orderFilter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockRepository_CountOrdersByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountOrdersByUserID'
type MockRepository_CountOrdersByUserID_Call struct {
	*mock.Call
}

// CountOrdersByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderFilter entities.OrderFilter
func (_e *MockRepository_Expecter) CountOrdersByUserID(ctx any, orderFilter any) *MockRepository_CountOrdersByUserID_Call {
	return &MockRepository_CountOrdersByUserID_Call{Call: _e.mock.On("CountOrdersByUserID", ctx, orderFilter)}
}

func (_c *MockRepository_CountOrdersByUserID_Call) Run(run func(ctx context.Context, orderFilter entities.OrderFilter)) *MockRepository_CountOrdersByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.OrderFilter
		if args[1] != nil {
			arg1 = args[1].(entities.OrderFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CountOrdersByUserID_Call) Return(n int32, domainError *entities.DomainError) *MockRepository_CountOrdersByUserID_Call {
	_c.Call.Return(n, domainError)
	return _c
}

func (_c *MockRepository_CountOrdersByUserID_Call) RunAndReturn(run func(ctx context.Context, orderFilter entities.OrderFilter) (int32, *entities.DomainError)) *MockRepository_CountOrdersByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateOrder(ctx context.Context, orderID string, userID int32, status entities.OrderStatus) *entities.DomainError {
	ret := _mock.Called(ctx, orderID, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32, entities.OrderStatus) *entities.DomainError); ok {
		r0 = returnFunc(ctx, orderID, userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DomainError)
		}
	}
	return r0
}

// MockRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - userID int32
//   - status entities.OrderStatus
func (_e *MockRepository_Expecter) CreateOrder(ctx any, orderID any, userID any, status any) *MockRepository_CreateOrder_Call {
	return &MockRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, orderID, userID, status)}
}

func (_c *MockRepository_CreateOrder_Call) Run(run func(ctx context.Context, orderID string, userID int32, status entities.OrderStatus)) *MockRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 entities.OrderStatus
		if args[3] != nil {
			arg3 = args[3].(entities.OrderStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_CreateOrder_Call) Return(domainError *entities.DomainError) *MockRepository_CreateOrder_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockRepository_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string, userID int32, status entities.OrderStatus) *entities.DomainError) *MockRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrderWithWithdraw provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateOrderWithWithdraw(ctx context.Context, userID int32, orderID string, bonusSum float64) *entities.DomainError {
	ret := _mock.Called(ctx, userID, orderID, bonusSum)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrderWithWithdraw")
	}

	var r0 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, string, float64) *entities.DomainError); ok {
		r0 = returnFunc(ctx, userID, orderID, bonusSum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DomainError)
		}
	}
	return r0
}

// MockRepository_CreateOrderWithWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrderWithWithdraw'
type MockRepository_CreateOrderWithWithdraw_Call struct {
	*mock.Call
}

// CreateOrderWithWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
//   - orderID string
//   - bonusSum float64
func (_e *MockRepository_Expecter) CreateOrderWithWithdraw(ctx any, userID any, orderID any, bonusSum any) *MockRepository_CreateOrderWithWithdraw_Call {
	return &MockRepository_CreateOrderWithWithdraw_Call{Call: _e.mock.On("CreateOrderWithWithdraw", ctx, userID, orderID, bonusSum)}
}

func (_c *MockRepository_CreateOrderWithWithdraw_Call) Run(run func(ctx context.Context, userID int32, orderID string, bonusSum float64)) *MockRepository_CreateOrderWithWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_CreateOrderWithWithdraw_Call) Return(domainError *entities.DomainError) *MockRepository_CreateOrderWithWithdraw_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockRepository_CreateOrderWithWithdraw_Call) RunAndReturn(run func(ctx context.Context, userID int32, orderID string, bonusSum float64) *entities.DomainError) *MockRepository_CreateOrderWithWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrderID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByOrderID(ctx context.Context, orderID string) (*entities.Order, *entities.DomainError) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 *entities.Order
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Order, *entities.DomainError)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *entities.DomainError); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockRepository_FindByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderID'
type MockRepository_FindByOrderID_Call struct {
	*mock.Call
}

// FindByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockRepository_Expecter) FindByOrderID(ctx any, orderID any) *MockRepository_FindByOrderID_Call {
	return &MockRepository_FindByOrderID_Call{Call: _e.mock.On("FindByOrderID", ctx, orderID)}
}

func (_c *MockRepository_FindByOrderID_Call) Run(run func(ctx context.Context, orderID string)) *MockRepository_FindByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByOrderID_Call) Return(order *entities.Order, domainError *entities.DomainError) *MockRepository_FindByOrderID_Call {
	_c.Call.Return(order, domainError)
	return _c
}

func (_c *MockRepository_FindByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*entities.Order, *entities.DomainError)) *MockRepository_FindByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByUserID(ctx context.Context, filter entities.OrderFilter, limit int64, offset int64) ([]entities.Order, *entities.DomainError) {
	ret := _mock.Called(ctx, filter, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []entities.Order
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.OrderFilter, int64, int64) ([]entities.Order, *entities.DomainError)); ok {
		return returnFunc(ctx, filter, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.OrderFilter, int64, int64) []entities.Order); ok {
		r0 = returnFunc(ctx, filter, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.OrderFilter, int64, int64) *entities.DomainError); ok {
		r1 = returnFunc(ctx, filter, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - filter entities.OrderFilter
//   - limit int64
//   - offset int64
func (_e *MockRepository_Expecter) FindByUserID(ctx any, filter any, limit any, offset any) *MockRepository_FindByUserID_Call {
	return &MockRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, filter, limit, offset)}
}

func (_c *MockRepository_FindByUserID_Call) Run(run func(ctx context.Context, filter entities.OrderFilter, limit int64, offset int64)) *MockRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.OrderFilter
		if args[1] != nil {
			arg1 = args[1].(entities.OrderFilter)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_FindByUserID_Call) Return(orders []entities.Order, domainError *entities.DomainError) *MockRepository_FindByUserID_Call {
	_c.Call.Return(orders, domainError)
	return _c
}

func (_c *MockRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, filter entities.OrderFilter, limit int64, offset int64) ([]entities.Order, *entities.DomainError)) *MockRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UserBalance provides a mock function for the type MockRepository
func (_mock *MockRepository) UserBalance(ctx context.Context, id int32) (float64, *entities.DomainError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserBalance")
	}

	var r0 float64
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (float64, *entities.DomainError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) float64); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) *entities.DomainError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockRepository_UserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserBalance'
type MockRepository_UserBalance_Call struct {
	*mock.Call
}

// UserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) UserBalance(ctx any, id any) *MockRepository_UserBalance_Call {
	return &MockRepository_UserBalance_Call{Call: _e.mock.On("UserBalance", ctx, id)}
}

func (_c *MockRepository_UserBalance_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_UserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UserBalance_Call) Return(f float64, domainError *entities.DomainError) *MockRepository_UserBalance_Call {
	_c.Call.Return(f, domainError)
	return _c
}

func (_c *MockRepository_UserBalance_Call) RunAndReturn(run func(ctx context.Context, id int32) (float64, *entities.DomainError)) *MockRepository_UserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// UserBalanceWithWithdrawn provides a mock function for the type MockRepository
func (_mock *MockRepository) UserBalanceWithWithdrawn(ctx context.Context, id int32) (entities.Balance, *entities.DomainError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceWithWithdrawn")
	}

	var r0 entities.Balance
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (entities.Balance, *entities.DomainError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) entities.Balance); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Balance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) *entities.DomainError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockRepository_UserBalanceWithWithdrawn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserBalanceWithWithdrawn'
type MockRepository_UserBalanceWithWithdrawn_Call struct {
	*mock.Call
}

// UserBalanceWithWithdrawn is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockRepository_Expecter) UserBalanceWithWithdrawn(ctx any, id any) *MockRepository_UserBalanceWithWithdrawn_Call {
	return &MockRepository_UserBalanceWithWithdrawn_Call{Call: _e.mock.On("UserBalanceWithWithdrawn", ctx, id)}
}

func (_c *MockRepository_UserBalanceWithWithdrawn_Call) Run(run func(ctx context.Context, id int32)) *MockRepository_UserBalanceWithWithdrawn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UserBalanceWithWithdrawn_Call) Return(balance entities.Balance, domainError *entities.DomainError) *MockRepository_UserBalanceWithWithdrawn_Call {
	_c.Call.Return(balance, domainError)
	return _c
}

func (_c *MockRepository_UserBalanceWithWithdrawn_Call) RunAndReturn(run func(ctx context.Context, id int32) (entities.Balance, *entities.DomainError)) *MockRepository_UserBalanceWithWithdrawn_Call {
	_c.Call.Return(run)
	return _c
}
