// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bazueva/gofermart/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBonusRepository creates a new instance of MockBonusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBonusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBonusRepository {
	mock := &MockBonusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBonusRepository is an autogenerated mock type for the BonusRepository type
type MockBonusRepository struct {
	mock.Mock
}

type MockBonusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBonusRepository) EXPECT() *MockBonusRepository_Expecter {
	return &MockBonusRepository_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type MockBonusRepository
func (_mock *MockBonusRepository) GetOrder(ctx context.Context, orderID string) (*entities.Order, *entities.DomainError) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *entities.Order
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Order, *entities.DomainError)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *entities.DomainError); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockBonusRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockBonusRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockBonusRepository_Expecter) GetOrder(ctx any, orderID any) *MockBonusRepository_GetOrder_Call {
	return &MockBonusRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderID)}
}

func (_c *MockBonusRepository_GetOrder_Call) Run(run func(ctx context.Context, orderID string)) *MockBonusRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBonusRepository_GetOrder_Call) Return(order *entities.Order, domainError *entities.DomainError) *MockBonusRepository_GetOrder_Call {
	_c.Call.Return(order, domainError)
	return _c
}

func (_c *MockBonusRepository_GetOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*entities.Order, *entities.DomainError)) *MockBonusRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}
