// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bazueva/gofermart/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// FindStaleOrders provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindStaleOrders(ctx context.Context, statuses []entities.OrderStatus, limit int64) ([]string, *entities.DomainError) {
	ret := _mock.Called(ctx, statuses, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindStaleOrders")
	}

	var r0 []string
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entities.OrderStatus, int64) ([]string, *entities.DomainError)); ok {
		return returnFunc(ctx, statuses, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entities.OrderStatus, int64) []string); ok {
		r0 = returnFunc(ctx, statuses, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []entities.OrderStatus, int64) *entities.DomainError); ok {
		r1 = returnFunc(ctx, statuses, limit)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockOrderRepository_FindStaleOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindStaleOrders'
type MockOrderRepository_FindStaleOrders_Call struct {
	*mock.Call
}

// FindStaleOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - statuses []entities.OrderStatus
//   - limit int64
func (_e *MockOrderRepository_Expecter) FindStaleOrders(ctx any, statuses any, limit any) *MockOrderRepository_FindStaleOrders_Call {
	return &MockOrderRepository_FindStaleOrders_Call{Call: _e.mock.On("FindStaleOrders", ctx, statuses, limit)}
}

func (_c *MockOrderRepository_FindStaleOrders_Call) Run(run func(ctx context.Context, statuses []entities.OrderStatus, limit int64)) *MockOrderRepository_FindStaleOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entities.OrderStatus
		if args[1] != nil {
			arg1 = args[1].([]entities.OrderStatus)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindStaleOrders_Call) Return(strings []string, domainError *entities.DomainError) *MockOrderRepository_FindStaleOrders_Call {
	_c.Call.Return(strings, domainError)
	return _c
}

func (_c *MockOrderRepository_FindStaleOrders_Call) RunAndReturn(run func(ctx context.Context, statuses []entities.OrderStatus, limit int64) ([]string, *entities.DomainError)) *MockOrderRepository_FindStaleOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusAndBonus provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) UpdateStatusAndBonus(ctx context.Context, order entities.Order) *entities.DomainError {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusAndBonus")
	}

	var r0 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Order) *entities.DomainError); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DomainError)
		}
	}
	return r0
}

// MockOrderRepository_UpdateStatusAndBonus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusAndBonus'
type MockOrderRepository_UpdateStatusAndBonus_Call struct {
	*mock.Call
}

// UpdateStatusAndBonus is a helper method to define mock.On call
//   - ctx context.Context
//   - order entities.Order
func (_e *MockOrderRepository_Expecter) UpdateStatusAndBonus(ctx any, order any) *MockOrderRepository_UpdateStatusAndBonus_Call {
	return &MockOrderRepository_UpdateStatusAndBonus_Call{Call: _e.mock.On("UpdateStatusAndBonus", ctx, order)}
}

func (_c *MockOrderRepository_UpdateStatusAndBonus_Call) Run(run func(ctx context.Context, order entities.Order)) *MockOrderRepository_UpdateStatusAndBonus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Order
		if args[1] != nil {
			arg1 = args[1].(entities.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_UpdateStatusAndBonus_Call) Return(domainError *entities.DomainError) *MockOrderRepository_UpdateStatusAndBonus_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockOrderRepository_UpdateStatusAndBonus_Call) RunAndReturn(run func(ctx context.Context, order entities.Order) *entities.DomainError) *MockOrderRepository_UpdateStatusAndBonus_Call {
	_c.Call.Return(run)
	return _c
}
