// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bazueva/gofermart/internal/domain/entities"
	"github.com/bazueva/gofermart/internal/domain/pagination"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// BalanceWithdraw provides a mock function for the type MockOrderService
func (_mock *MockOrderService) BalanceWithdraw(ctx context.Context, userID int32, withdraw entities.BalanceWithdraw) *entities.DomainError {
	ret := _mock.Called(ctx, userID, withdraw)

	if len(ret) == 0 {
		panic("no return value specified for BalanceWithdraw")
	}

	var r0 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, entities.BalanceWithdraw) *entities.DomainError); ok {
		r0 = returnFunc(ctx, userID, withdraw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DomainError)
		}
	}
	return r0
}

// MockOrderService_BalanceWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceWithdraw'
type MockOrderService_BalanceWithdraw_Call struct {
	*mock.Call
}

// BalanceWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
//   - withdraw entities.BalanceWithdraw
func (_e *MockOrderService_Expecter) BalanceWithdraw(ctx any, userID any, withdraw any) *MockOrderService_BalanceWithdraw_Call {
	return &MockOrderService_BalanceWithdraw_Call{Call: _e.mock.On("BalanceWithdraw", ctx, userID, withdraw)}
}

func (_c *MockOrderService_BalanceWithdraw_Call) Run(run func(ctx context.Context, userID int32, withdraw entities.BalanceWithdraw)) *MockOrderService_BalanceWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 entities.BalanceWithdraw
		if args[2] != nil {
			arg2 = args[2].(entities.BalanceWithdraw)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderService_BalanceWithdraw_Call) Return(domainError *entities.DomainError) *MockOrderService_BalanceWithdraw_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockOrderService_BalanceWithdraw_Call) RunAndReturn(run func(ctx context.Context, userID int32, withdraw entities.BalanceWithdraw) *entities.DomainError) *MockOrderService_BalanceWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function for the type MockOrderService
func (_mock *MockOrderService) CreateOrder(ctx context.Context, orderID string, userID int32) *entities.DomainError {
	ret := _mock.Called(ctx, orderID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int32) *entities.DomainError); ok {
		r0 = returnFunc(ctx, orderID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DomainError)
		}
	}
	return r0
}

// MockOrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - userID int32
func (_e *MockOrderService_Expecter) CreateOrder(ctx any, orderID any, userID any) *MockOrderService_CreateOrder_Call {
	return &MockOrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, orderID, userID)}
}

func (_c *MockOrderService_CreateOrder_Call) Run(run func(ctx context.Context, orderID string, userID int32)) *MockOrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) Return(domainError *entities.DomainError) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockOrderService_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, orderID string, userID int32) *entities.DomainError) *MockOrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// OrdersListUser provides a mock function for the type MockOrderService
func (_mock *MockOrderService) OrdersListUser(ctx context.Context, userID int32, pagination1 *pagination.Pagination) ([]entities.Order, *entities.DomainError) {
	ret := _mock.Called(ctx, userID, pagination1)

	if len(ret) == 0 {
		panic("no return value specified for OrdersListUser")
	}

	var r0 []entities.Order
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, *pagination.Pagination) ([]entities.Order, *entities.DomainError)); ok {
		return returnFunc(ctx, userID, pagination1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, *pagination.Pagination) []entities.Order); ok {
		r0 = returnFunc(ctx, userID, pagination1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, *pagination.Pagination) *entities.DomainError); ok {
		r1 = returnFunc(ctx, userID, pagination1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockOrderService_OrdersListUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrdersListUser'
type MockOrderService_OrdersListUser_Call struct {
	*mock.Call
}

// OrdersListUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
//   - pagination1 *pagination.Pagination
func (_e *MockOrderService_Expecter) OrdersListUser(ctx any, userID any, pagination1 any) *MockOrderService_OrdersListUser_Call {
	return &MockOrderService_OrdersListUser_Call{Call: _e.mock.On("OrdersListUser", ctx, userID, pagination1)}
}

func (_c *MockOrderService_OrdersListUser_Call) Run(run func(ctx context.Context, userID int32, pagination1 *pagination.Pagination)) *MockOrderService_OrdersListUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 *pagination.Pagination
		if args[2] != nil {
			arg2 = args[2].(*pagination.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderService_OrdersListUser_Call) Return(orders []entities.Order, domainError *entities.DomainError) *MockOrderService_OrdersListUser_Call {
	_c.Call.Return(orders, domainError)
	return _c
}

func (_c *MockOrderService_OrdersListUser_Call) RunAndReturn(run func(ctx context.Context, userID int32, pagination1 *pagination.Pagination) ([]entities.Order, *entities.DomainError)) *MockOrderService_OrdersListUser_Call {
	_c.Call.Return(run)
	return _c
}

// OrdersWithdrawalsListUser provides a mock function for the type MockOrderService
func (_mock *MockOrderService) OrdersWithdrawalsListUser(ctx context.Context, userID int32, newPagination *pagination.Pagination) ([]entities.Order, *entities.DomainError) {
	ret := _mock.Called(ctx, userID, newPagination)

	if len(ret) == 0 {
		panic("no return value specified for OrdersWithdrawalsListUser")
	}

	var r0 []entities.Order
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, *pagination.Pagination) ([]entities.Order, *entities.DomainError)); ok {
		return returnFunc(ctx, userID, newPagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, *pagination.Pagination) []entities.Order); ok {
		r0 = returnFunc(ctx, userID, newPagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32, *pagination.Pagination) *entities.DomainError); ok {
		r1 = returnFunc(ctx, userID, newPagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockOrderService_OrdersWithdrawalsListUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrdersWithdrawalsListUser'
type MockOrderService_OrdersWithdrawalsListUser_Call struct {
	*mock.Call
}

// OrdersWithdrawalsListUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
//   - newPagination *pagination.Pagination
func (_e *MockOrderService_Expecter) OrdersWithdrawalsListUser(ctx any, userID any, newPagination any) *MockOrderService_OrdersWithdrawalsListUser_Call {
	return &MockOrderService_OrdersWithdrawalsListUser_Call{Call: _e.mock.On("OrdersWithdrawalsListUser", ctx, userID, newPagination)}
}

func (_c *MockOrderService_OrdersWithdrawalsListUser_Call) Run(run func(ctx context.Context, userID int32, newPagination *pagination.Pagination)) *MockOrderService_OrdersWithdrawalsListUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 *pagination.Pagination
		if args[2] != nil {
			arg2 = args[2].(*pagination.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderService_OrdersWithdrawalsListUser_Call) Return(orders []entities.Order, domainError *entities.DomainError) *MockOrderService_OrdersWithdrawalsListUser_Call {
	_c.Call.Return(orders, domainError)
	return _c
}

func (_c *MockOrderService_OrdersWithdrawalsListUser_Call) RunAndReturn(run func(ctx context.Context, userID int32, newPagination *pagination.Pagination) ([]entities.Order, *entities.DomainError)) *MockOrderService_OrdersWithdrawalsListUser_Call {
	_c.Call.Return(run)
	return _c
}

// UserBalance provides a mock function for the type MockOrderService
func (_mock *MockOrderService) UserBalance(ctx context.Context, id int32) (entities.Balance, *entities.DomainError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserBalance")
	}

	var r0 entities.Balance
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (entities.Balance, *entities.DomainError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) entities.Balance); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Balance)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) *entities.DomainError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockOrderService_UserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserBalance'
type MockOrderService_UserBalance_Call struct {
	*mock.Call
}

// UserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockOrderService_Expecter) UserBalance(ctx any, id any) *MockOrderService_UserBalance_Call {
	return &MockOrderService_UserBalance_Call{Call: _e.mock.On("UserBalance", ctx, id)}
}

func (_c *MockOrderService_UserBalance_Call) Run(run func(ctx context.Context, id int32)) *MockOrderService_UserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderService_UserBalance_Call) Return(balance entities.Balance, domainError *entities.DomainError) *MockOrderService_UserBalance_Call {
	_c.Call.Return(balance, domainError)
	return _c
}

func (_c *MockOrderService_UserBalance_Call) RunAndReturn(run func(ctx context.Context, id int32) (entities.Balance, *entities.DomainError)) *MockOrderService_UserBalance_Call {
	_c.Call.Return(run)
	return _c
}
