// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bazueva/gofermart/internal/domain/entities"
	"github.com/bazueva/gofermart/internal/models/forms"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CheckJWTToken provides a mock function for the type MockUserService
func (_mock *MockUserService) CheckJWTToken(token string) (int32, *entities.DomainError) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for CheckJWTToken")
	}

	var r0 int32
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(string) (int32, *entities.DomainError)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int32); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(string) *entities.DomainError); ok {
		r1 = returnFunc(token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockUserService_CheckJWTToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckJWTToken'
type MockUserService_CheckJWTToken_Call struct {
	*mock.Call
}

// CheckJWTToken is a helper method to define mock.On call
//   - token string
func (_e *MockUserService_Expecter) CheckJWTToken(token any) *MockUserService_CheckJWTToken_Call {
	return &MockUserService_CheckJWTToken_Call{Call: _e.mock.On("CheckJWTToken", token)}
}

func (_c *MockUserService_CheckJWTToken_Call) Run(run func(token string)) *MockUserService_CheckJWTToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_CheckJWTToken_Call) Return(n int32, domainError *entities.DomainError) *MockUserService_CheckJWTToken_Call {
	_c.Call.Return(n, domainError)
	return _c
}

func (_c *MockUserService_CheckJWTToken_Call) RunAndReturn(run func(token string) (int32, *entities.DomainError)) *MockUserService_CheckJWTToken_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockUserService
func (_mock *MockUserService) Login(ctx context.Context, user forms.LoginForm) (string, *entities.DomainError) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, forms.LoginForm) (string, *entities.DomainError)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, forms.LoginForm) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, forms.LoginForm) *entities.DomainError); ok {
		r1 = returnFunc(ctx, user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockUserService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - user forms.LoginForm
func (_e *MockUserService_Expecter) Login(ctx any, user any) *MockUserService_Login_Call {
	return &MockUserService_Login_Call{Call: _e.mock.On("Login", ctx, user)}
}

func (_c *MockUserService_Login_Call) Run(run func(ctx context.Context, user forms.LoginForm)) *MockUserService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 forms.LoginForm
		if args[1] != nil {
			arg1 = args[1].(forms.LoginForm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Login_Call) Return(s string, domainError *entities.DomainError) *MockUserService_Login_Call {
	_c.Call.Return(s, domainError)
	return _c
}

func (_c *MockUserService_Login_Call) RunAndReturn(run func(ctx context.Context, user forms.LoginForm) (string, *entities.DomainError)) *MockUserService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserService
func (_mock *MockUserService) Register(ctx context.Context, user forms.UserForm) (string, *entities.DomainError) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, forms.UserForm) (string, *entities.DomainError)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, forms.UserForm) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, forms.UserForm) *entities.DomainError); ok {
		r1 = returnFunc(ctx, user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - user forms.UserForm
func (_e *MockUserService_Expecter) Register(ctx any, user any) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, user)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, user forms.UserForm)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 forms.UserForm
		if args[1] != nil {
			arg1 = args[1].(forms.UserForm)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(s string, domainError *entities.DomainError) *MockUserService_Register_Call {
	_c.Call.Return(s, domainError)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(ctx context.Context, user forms.UserForm) (string, *entities.DomainError)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
