// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bazueva/gofermart/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateUser(ctx context.Context, user entities.User) (int32, *entities.DomainError) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int32
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.User) (int32, *entities.DomainError)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.User) int32); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.User) *entities.DomainError); ok {
		r1 = returnFunc(ctx, user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user entities.User
func (_e *MockRepository_Expecter) CreateUser(ctx any, user any) *MockRepository_CreateUser_Call {
	return &MockRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockRepository_CreateUser_Call) Run(run func(ctx context.Context, user entities.User)) *MockRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.User
		if args[1] != nil {
			arg1 = args[1].(entities.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateUser_Call) Return(n int32, domainError *entities.DomainError) *MockRepository_CreateUser_Call {
	_c.Call.Return(n, domainError)
	return _c
}

func (_c *MockRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user entities.User) (int32, *entities.DomainError)) *MockRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExistLogin provides a mock function for the type MockRepository
func (_mock *MockRepository) ExistLogin(ctx context.Context, login string) (bool, *entities.DomainError) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for ExistLogin")
	}

	var r0 bool
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, *entities.DomainError)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *entities.DomainError); ok {
		r1 = returnFunc(ctx, login)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockRepository_ExistLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistLogin'
type MockRepository_ExistLogin_Call struct {
	*mock.Call
}

// ExistLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockRepository_Expecter) ExistLogin(ctx any, login any) *MockRepository_ExistLogin_Call {
	return &MockRepository_ExistLogin_Call{Call: _e.mock.On("ExistLogin", ctx, login)}
}

func (_c *MockRepository_ExistLogin_Call) Run(run func(ctx context.Context, login string)) *MockRepository_ExistLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ExistLogin_Call) Return(b bool, domainError *entities.DomainError) *MockRepository_ExistLogin_Call {
	_c.Call.Return(b, domainError)
	return _c
}

func (_c *MockRepository_ExistLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (bool, *entities.DomainError)) *MockRepository_ExistLogin_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLogin provides a mock function for the type MockRepository
func (_mock *MockRepository) FindByLogin(ctx context.Context, login string) (entities.User, *entities.DomainError) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for FindByLogin")
	}

	var r0 entities.User
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.User, *entities.DomainError)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.User); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(entities.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *entities.DomainError); ok {
		r1 = returnFunc(ctx, login)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockRepository_FindByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLogin'
type MockRepository_FindByLogin_Call struct {
	*mock.Call
}

// FindByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockRepository_Expecter) FindByLogin(ctx any, login any) *MockRepository_FindByLogin_Call {
	return &MockRepository_FindByLogin_Call{Call: _e.mock.On("FindByLogin", ctx, login)}
}

func (_c *MockRepository_FindByLogin_Call) Run(run func(ctx context.Context, login string)) *MockRepository_FindByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindByLogin_Call) Return(user entities.User, domainError *entities.DomainError) *MockRepository_FindByLogin_Call {
	_c.Call.Return(user, domainError)
	return _c
}

func (_c *MockRepository_FindByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (entities.User, *entities.DomainError)) *MockRepository_FindByLogin_Call {
	_c.Call.Return(run)
	return _c
}
