//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var OrdersStatus = &struct {
	New        postgres.StringExpression
	Processing postgres.StringExpression
	Invalid    postgres.StringExpression
	Processed  postgres.StringExpression
}{
	New:        postgres.NewEnumValue("NEW"),
	Processing: postgres.NewEnumValue("PROCESSING"),
	Invalid:    postgres.NewEnumValue("INVALID"),
	Processed:  postgres.NewEnumValue("PROCESSED"),
}
