//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type OrdersStatus string

const (
	OrdersStatus_New        OrdersStatus = "NEW"
	OrdersStatus_Processing OrdersStatus = "PROCESSING"
	OrdersStatus_Invalid    OrdersStatus = "INVALID"
	OrdersStatus_Processed  OrdersStatus = "PROCESSED"
)

var OrdersStatusAllValues = []OrdersStatus{
	OrdersStatus_New,
	OrdersStatus_Processing,
	OrdersStatus_Invalid,
	OrdersStatus_Processed,
}

func (e *OrdersStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "NEW":
		*e = OrdersStatus_New
	case "PROCESSING":
		*e = OrdersStatus_Processing
	case "INVALID":
		*e = OrdersStatus_Invalid
	case "PROCESSED":
		*e = OrdersStatus_Processed
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for OrdersStatus enum")
	}

	return nil
}

func (e OrdersStatus) String() string {
	return string(e)
}
