//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Orders struct {
	ID          int32 `sql:"primary_key"`
	OrderID     string
	Status      OrdersStatus
	UserID      int32
	BonusSum    *float64
	CreatedAt   *time.Time
	ProcessedAt *time.Time
	UpdatedAt   *time.Time
	NextCheckAt *time.Time
}
