//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Orders = newOrdersTable("public", "orders", "")

type ordersTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	OrderID     postgres.ColumnString
	Status      postgres.ColumnString
	UserID      postgres.ColumnInteger
	BonusSum    postgres.ColumnFloat
	CreatedAt   postgres.ColumnTimestampz
	ProcessedAt postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz
	NextCheckAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OrdersTable struct {
	ordersTable

	EXCLUDED ordersTable
}

// AS creates new OrdersTable with assigned alias
func (a OrdersTable) AS(alias string) *OrdersTable {
	return newOrdersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OrdersTable with assigned schema name
func (a OrdersTable) FromSchema(schemaName string) *OrdersTable {
	return newOrdersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OrdersTable with assigned table prefix
func (a OrdersTable) WithPrefix(prefix string) *OrdersTable {
	return newOrdersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OrdersTable with assigned table suffix
func (a OrdersTable) WithSuffix(suffix string) *OrdersTable {
	return newOrdersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOrdersTable(schemaName, tableName, alias string) *OrdersTable {
	return &OrdersTable{
		ordersTable: newOrdersTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newOrdersTableImpl("", "excluded", ""),
	}
}

func newOrdersTableImpl(schemaName, tableName, alias string) ordersTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		OrderIDColumn     = postgres.StringColumn("order_id")
		StatusColumn      = postgres.StringColumn("status")
		UserIDColumn      = postgres.IntegerColumn("user_id")
		BonusSumColumn    = postgres.FloatColumn("bonus_sum")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		ProcessedAtColumn = postgres.TimestampzColumn("processed_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		NextCheckAtColumn = postgres.TimestampzColumn("next_check_at")
		allColumns        = postgres.ColumnList{IDColumn, OrderIDColumn, StatusColumn, UserIDColumn, BonusSumColumn, CreatedAtColumn, ProcessedAtColumn, UpdatedAtColumn, NextCheckAtColumn}
		mutableColumns    = postgres.ColumnList{OrderIDColumn, StatusColumn, UserIDColumn, BonusSumColumn, CreatedAtColumn, ProcessedAtColumn, UpdatedAtColumn, NextCheckAtColumn}
		defaultColumns    = postgres.ColumnList{CreatedAtColumn, UpdatedAtColumn}
	)

	return ordersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		OrderID:     OrderIDColumn,
		Status:      StatusColumn,
		UserID:      UserIDColumn,
		BonusSum:    BonusSumColumn,
		CreatedAt:   CreatedAtColumn,
		ProcessedAt: ProcessedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		NextCheckAt: NextCheckAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
