// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bazueva/gofermart/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCheckerJWTToken creates a new instance of MockCheckerJWTToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckerJWTToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckerJWTToken {
	mock := &MockCheckerJWTToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckerJWTToken is an autogenerated mock type for the CheckerJWTToken type
type MockCheckerJWTToken struct {
	mock.Mock
}

type MockCheckerJWTToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckerJWTToken) EXPECT() *MockCheckerJWTToken_Expecter {
	return &MockCheckerJWTToken_Expecter{mock: &_m.Mock}
}

// CheckJWTToken provides a mock function for the type MockCheckerJWTToken
func (_mock *MockCheckerJWTToken) CheckJWTToken(token string) (int32, *entities.DomainError) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for CheckJWTToken")
	}

	var r0 int32
	var r1 *entities.DomainError
	if returnFunc, ok := ret.Get(0).(func(string) (int32, *entities.DomainError)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int32); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(string) *entities.DomainError); ok {
		r1 = returnFunc(token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.DomainError)
		}
	}
	return r0, r1
}

// MockCheckerJWTToken_CheckJWTToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckJWTToken'
type MockCheckerJWTToken_CheckJWTToken_Call struct {
	*mock.Call
}

// CheckJWTToken is a helper method to define mock.On call
//   - token string
func (_e *MockCheckerJWTToken_Expecter) CheckJWTToken(token any) *MockCheckerJWTToken_CheckJWTToken_Call {
	return &MockCheckerJWTToken_CheckJWTToken_Call{Call: _e.mock.On("CheckJWTToken", token)}
}

func (_c *MockCheckerJWTToken_CheckJWTToken_Call) Run(run func(token string)) *MockCheckerJWTToken_CheckJWTToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCheckerJWTToken_CheckJWTToken_Call) Return(n int32, domainError *entities.DomainError) *MockCheckerJWTToken_CheckJWTToken_Call {
	_c.Call.Return(n, domainError)
	return _c
}

func (_c *MockCheckerJWTToken_CheckJWTToken_Call) RunAndReturn(run func(token string) (int32, *entities.DomainError)) *MockCheckerJWTToken_CheckJWTToken_Call {
	_c.Call.Return(run)
	return _c
}
